package main

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
)

const procstatFilePath string = "/proc/stat"

type CPUTime struct {
	UserTime   int
	NiceTime   int
	SystemTime int
	IdleTime   int
}

// /proc/stat file is generated by kernel and give informations about the cpu.
// The first line of this file contains the amount of time that the CPU spent computing various tasks.
// Format of the file : [CPU] | [USER] | [NICE] | [SYSTEM] | [IDLE] | [...]
func getCPUTime(procstatContent string) CPUTime {
	var ct CPUTime
	var err error

	// match single or double space to trim /proc/stat first line
	re := regexp.MustCompile("  | ")
	cpuLine := re.Split(strings.Split(procstatContent, "\n")[0], -1)

	ct.UserTime, err = strconv.Atoi(cpuLine[1])
	if err != nil {
		log.Fatal(err)
	}

	ct.NiceTime, err = strconv.Atoi(cpuLine[2])
	if err != nil {
		log.Fatal(err)
	}

	ct.SystemTime, err = strconv.Atoi(cpuLine[3])
	if err != nil {
		log.Fatal(err)
	}

	ct.IdleTime, err = strconv.Atoi(cpuLine[4])
	if err != nil {
		log.Fatal(err)
	}

	return ct
}

func getCPUUsage(current, previous CPUTime) float64 {
	currentUsage := current.UserTime + current.NiceTime + current.SystemTime + current.IdleTime
	previousUsage := previous.UserTime + previous.NiceTime + previous.SystemTime + previous.IdleTime

	deltaUsage := currentUsage - previousUsage
	deltaIdle := current.IdleTime - previous.IdleTime
	usage := (1.0 - float64(deltaIdle)/float64(deltaUsage)) * 100.0
	return usage
}

var previous CPUTime

func getCPUPercentage() float64 {
	var cpuPercent float64 = 0
	procstatContent, err := ReadFile(procstatFilePath)
	if err != nil {
		log.Fatal(fmt.Sprintf("Cannot open file %s - %v", procstatFilePath), err)
	}

	cpuTime := getCPUTime(procstatContent)

	if (CPUTime{}) != previous {
		cpuPercent = getCPUUsage(cpuTime, previous)
	}
	previous = cpuTime
	return cpuPercent
}
